<?php

namespace Meggi\IndexBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use FOS\UserBundle\Entity\User;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends EntityRepository
{
    public function deleteOrder($orderId, User $user)
    {
        $this->getEntityManager()
            ->createQueryBuilder()
            ->delete('MeggiIndexBundle:Orders', 'o')
            ->andWhere('o.id = :orderId')
            ->andWhere('o.user = :user')
            ->setParameter('orderId', $orderId)
            ->setParameter('user', $user)
            ->getQuery()
            ->execute();
    }

    public function getOrdersByUser($user)
    {
        $qb = $this->createQueryBuilder('o')
            ->leftJoin('o.user', 'user')
            ->andWhere('user = :user')
            ->setParameter('user', $user)
            ->orderBy('o.id', 'desc');

        return $qb->getQuery()->getResult();
    }
}
